name: dockerhub-publish

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-push-specific:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_image: ['ubuntu:22.04']
        llvm_version: [17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get the latest commit hash
        id: git_commit
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Build and push specific Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            quanttide/quanttide-docker-image-of-clang:${{ steps.git_commit.outputs.short_sha }}-${{ matrix.base_image }}-llvm${{ matrix.llvm_version }}
            quanttide/quanttide-docker-image-of-clang:latest-${{ matrix.base_image }}-llvm${{ matrix.llvm_version }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            LLVM_VERSION=${{ matrix.llvm_version }}

  build-and-push-default-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get the latest commit hash
        id: git_commit
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Build and push default latest Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            quanttide/quanttide-docker-image-of-clang:${{ steps.git_commit.outputs.short_sha }}
            quanttide/quanttide-docker-image-of-clang:latest